### ISSUE TITLE
Path issue on Windows

### ISSUE THREAD

**Issue by eleo-jens** [nemishmehta/automate_splitwise_expenses#2]
There is an error while trying to create the clean CSV file in a new directory: 
"OSError: Cannot save file into a non-existent directory: 'C:\Users\name\Documents\Projetcs\automate_splitwise_expenses\src\data\clean\C:\Users\name\Downloads''
The last part of the path is not correct, it should be the name of the CSV file.

**Comment by nemishmehta** [comment]
I have updated the write_output_file method to consider file path formats for Windows based systems. The latest changes should resolve your issue.
